{"version":3,"file":"static/chunks/pages/_error-fb7fb4bf8d1c0424.js","mappings":"wFACKA,OAAOC,SAAWD,OAAOC,UAAY,IAAIC,KAAK,CAC7C,UACA,WACE,OAAO,EAAQ,W,uOCAvB,IAAMC,EAAU,SAAQ,G,IAALC,EAAU,EAAVA,WAAYC,EAAqB,EAArBA,sBAAuBC,EAAG,EAAHA,IASpD,OARKD,GAAyBC,GAI5BC,EAAAA,GAAwBD,IAIpB,SAAEE,EAAAA,QAAkB,CAACJ,WAAYA,KAGzCD,EAAQM,gBAAkB,W,qBAAA,SAAS,EAAD,G,IAACC,EAAKJ,EAAKK,EACrCC,E,wEAD2BF,EAAG,EAAHA,IAAKJ,EAAG,EAAHA,IAAKK,EAAM,EAANA,O,SACXH,EAAAA,QAAAA,gBAAmC,CACjEE,IAAAA,EACAJ,IAAAA,I,WAFIM,EAAoB,EAAH,MAOLP,uBAAwB,GAetCC,EAAK,C,uBACPC,EAAAA,GAAwBD,G,SAIlBC,EAAAA,GAAa,K,wCAadK,G,eALPL,EAAAA,GACE,IAAIM,MAAO,mDAAyD,OAAPF,K,UAEzDJ,EAAAA,GAAa,K,6QAvCK,GA4C1B,a,sBC5DAO,EAAOC,QAAU,EAAjB,S","sources":["webpack://_N_E/?33da","webpack://_N_E/./pages/_error.js","webpack://_N_E/./node_modules/next/error.js"],"sourcesContent":["\n    (window.__NEXT_P = window.__NEXT_P || []).push([\n      \"/_error\",\n      function () {\n        return require(\"private-next-pages/_error.js\");\n      }\n    ]);\n    if(module.hot) {\n      module.hot.dispose(function () {\n        window.__NEXT_P.push([\"/_error\"])\n      });\n    }\n  ","import NextErrorComponent from \"next/error\";\n\nimport * as Sentry from \"@sentry/nextjs\";\n\nconst MyError = ({ statusCode, hasGetInitialPropsRun, err }) => {\n  if (!hasGetInitialPropsRun && err) {\n    // getInitialProps is not called in case of\n    // https://github.com/vercel/next.js/issues/8592. As a workaround, we pass\n    // err via _app.js so it can be captured\n    Sentry.captureException(err);\n    // Flushing is not required in this case as it only happens on the client\n  }\n\n  return <NextErrorComponent statusCode={statusCode} />;\n};\n\nMyError.getInitialProps = async ({ res, err, asPath }) => {\n  const errorInitialProps = await NextErrorComponent.getInitialProps({\n    res,\n    err,\n  });\n\n  // Workaround for https://github.com/vercel/next.js/issues/8592, mark when\n  // getInitialProps has run\n  errorInitialProps.hasGetInitialPropsRun = true;\n\n  // Running on the server, the response object (`res`) is available.\n  //\n  // Next.js will pass an err on the server if a page's data fetching methods\n  // threw or returned a Promise that rejected\n  //\n  // Running on the client (browser), Next.js will provide an err if:\n  //\n  //  - a page's `getInitialProps` threw or returned a Promise that rejected\n  //  - an exception was thrown somewhere in the React lifecycle (render,\n  //    componentDidMount, etc) that was caught by Next.js's React Error\n  //    Boundary. Read more about what types of exceptions are caught by Error\n  //    Boundaries: https://reactjs.org/docs/error-boundaries.html\n\n  if (err) {\n    Sentry.captureException(err);\n\n    // Flushing before returning is necessary if deploying to Vercel, see\n    // https://vercel.com/docs/platform/limits#streaming-responses\n    await Sentry.flush(2000);\n\n    return errorInitialProps;\n  }\n\n  // If this point is reached, getInitialProps was called without any\n  // information about what the error might be. This is unexpected and may\n  // indicate a bug introduced in Next.js, so record it in Sentry\n  Sentry.captureException(\n    new Error(`_error.js getInitialProps missing data at path: ${asPath}`)\n  );\n  await Sentry.flush(2000);\n\n  return errorInitialProps;\n};\n\nexport default MyError;\n","module.exports = require('./dist/pages/_error')\n"],"names":["window","__NEXT_P","push","MyError","statusCode","hasGetInitialPropsRun","err","Sentry","NextErrorComponent","getInitialProps","res","asPath","errorInitialProps","Error","module","exports"],"sourceRoot":""}